"""
Document Service
Assembles the agent output into a clean, structured Markdown document.
"""

import logging
from datetime import datetime

logger = logging.getLogger(__name__)


def assemble_markdown(agent_output: dict) -> str:
    """
    Converts agent pipeline output into a formatted Markdown document.

    Structure:
    - Title
    - Metadata
    - Abstract
    - Table of Contents
    - Sections (one per topic)
    - Key Takeaways
    - Conclusion
    """
    title = agent_output["title"]
    abstract = agent_output["abstract"]
    topics = agent_output["topics"]
    sections = agent_output["sections"]       # dict: {topic: content}
    takeaways = agent_output["takeaways"]     # list of strings
    conclusion = agent_output["conclusion"]

    date_str = datetime.now().strftime("%B %d, %Y")

    lines = []

    # ── Title ──
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"> 📅 Generated on {date_str} | 🤖 AI-Generated Educational Document")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Abstract ──
    lines.append("## 📌 Abstract")
    lines.append("")
    lines.append(abstract.strip())
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Table of Contents ──
    lines.append("## 📋 Table of Contents")
    lines.append("")
    for i, topic in enumerate(topics, 1):
        anchor = topic.lower().replace(" ", "-").replace(".", "")
        lines.append(f"{i}. [{topic}](#{anchor})")
    lines.append(f"{len(topics) + 1}. [Key Takeaways](#key-takeaways)")
    lines.append(f"{len(topics) + 2}. [Conclusion](#conclusion)")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Sections ──
    for i, topic in enumerate(topics, 1):
        content = sections.get(topic, "_Content not available._")
        lines.append(f"## {i}. {topic}")
        lines.append("")
        lines.append(content.strip())
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── Key Takeaways ──
    lines.append("## 💡 Key Takeaways")
    lines.append("")
    for takeaway in takeaways:
        lines.append(f"- {takeaway.strip()}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Conclusion ──
    lines.append("## 🎯 Conclusion")
    lines.append("")
    lines.append(conclusion.strip())
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*This document was automatically generated by the YouTube → Document AI Pipeline.*")

    document = "\n".join(lines)
    logger.info(f"Assembled Markdown document: {len(document)} chars")
    return document
